### ISSUE TITLE
Dependencies problem : react-lottie incompatible with react 17

### ISSUE THREAD

**Issue by kyro38** [Cosmo-Tech/azure-sample-webapp#92] opened 2021-07-06 19:05 UTC
As per npm : 

```
npm ERR! While resolving: csm-webapp-azure@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.7 || ^15.0.0 || ^16.0.0" from react-lottie@1.2.3
npm ERR! node_modules/react-lottie
npm ERR!   react-lottie@"^1.2.3" from the root project
```

**Comment by csm-thu** [comment] 2021-07-07 11:49
Hello ! Thank you for the feedback, we'll update this dependency when the issue is fixed on their side, or we'll find another library to replace it.
In the meantime, you can force the install of the dependencies with `npm i --force` or `yarn install`.

**Comment by csm-thu** [comment] 2021-12-06 10:24
`react-lottie` has been replaced by `react-lottie-player` and the dependency has been moved to the `cosmotech/ui` package

Closing this ticket

**Closed by csm-thu** 2021-12-06 10:24 UTC
Labels: bug
